services:
  finance-api:
    container_name: finance-api
    image: alysonsz/finance-api:v2.0.0
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__WriteDatabase=Server=finance-sqlserver-db;Database=FinanceDb;User Id=sa;Password=MyStrongPassword123!;TrustServerCertificate=True;Connect Timeout=30;
      - ConnectionStrings__ReadDatabase=Host=finance-postgre-db;Port=5432;Database=FinanceReadDb;Username=postgres;Password=MyStrongPassword123!;
      - Serilog__WriteTo__0__Args__serverUrl=http://finance-seq:5341
      - ASPNETCORE_DataProtection__KeyManagement__XmlRepository__Directory=/root/.aspnet/DataProtection-Keys
      - ConnectionStrings__Redis=finance-redis:6379
    ports:
      - "5000:8080"
    depends_on:
      finance-sqlserver:
        condition: service_healthy
      finance-postgre:
        condition: service_started
      finance-redis:
        condition: service_started
    volumes:
      - finance_keys:/root/.aspnet/DataProtection-Keys
    networks:
      finance-network:

  finance-sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: finance-sqlserver-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=MyStrongPassword123!
    ports:
      - "1433:1433"
    volumes:
      - finance_sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P 'MyStrongPassword123!' -Q 'SELECT 1' -C || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 60s
    networks:
      finance-network:
    
  finance-postgre:
    image: postgres:alpine
    container_name: finance-postgre-db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=MyStrongPassword123!
      - POSTGRES_DB=FinanceReadDb
    ports:
      - "5432:5432"
    networks:
      - finance-network

  finance-seq:
    image: datalust/seq:latest
    container_name: finance-seq
    environment:
      - ACCEPT_EULA=Y
      - SEQ_FIRSTRUN_ADMINPASSWORD=MyStrongPassword123!
    ports:
      - "5341:80" 
    networks:
      finance-network:
    
  finance-redis:
    image: redis:alpine
    container_name: finance-redis
    ports:
      - "6379:6379"
    restart: unless-stopped
    networks:
      finance-network:

volumes:
  finance_sql_data:
  finance_keys:

networks:
  finance-network:
